name: "Publish Resume"
on:
  push:
    branches:
      - master

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install the dependencies
        run: |
          apt-get update && apt-get install -y git
          pnpm i

      - name: Build the resume - html
        run: |
          pnpm run html

      - name: Deploy the resume - html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Build the resume - pdf
        run: |
          pnpm run pdf
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Andrew_Challis_Resume.pdf
          git commit -m "Publishing latest PDF"

      - name: Deploy the resume - pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
