name: "Publish Resume"
on:
  push:
    branches:
      - master

jobs:
  publish_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "11"

      - name: Install the dependencies
        run: |
          apt-get update && apt-get install -y git
          npm install resumed-cli
          git clone https://github.com/ghandic/jsonresume-theme-stackoverflow.git
          cd jsonresume-theme-stackoverflow
          npm install .
          cd ..
          mkdir public

      - name: Build the resume - html
        run: |
          npm cache clean --force
          ./node_modules/.bin/resumed export --theme stackoverflow --format html public/index.html

      - name: Deploy the resume - html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Build the resume - pdf
        run: |
          ./node_modules/.bin/resumed export --theme stackoverflow --format pdf Andrew_Challis_Resume.pdf
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Andrew_Challis_Resume.pdf
          git commit -m "Publishing latest PDF"

      - name: Deploy the resume - pdf
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
